server:
  port: 25000

  tomcat:
    max-connections: 500
    threads:
      max: 200
    accept-count: 100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 102030aoboco
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 6000MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
    map-underscore-to-camel-case: true

